Buildroot: /home/gbuades/soffid/console/install/target/soffid-iamconsole-3.0.0
Name: soffid-iamconsole
Version: ${parsedVersion.majorVersion}.${parsedVersion.minorVersion}.${parsedVersion.incrementalVersion}
Release: 1
Summary: Soffid IAM Console
License: GPL
Distribution: Soffid IAM
Group: Administration/Netwokr

%define _rpmdir target
%define _rpmfilename %%{NAME}-%%{VERSION}-%%{RELEASE}.%%{ARCH}.rpm
%define _unpackaged_files_terminate_build 0

%post
#!/bin/sh
set -e
if ! getent group soffid >/dev/null 2>&1; then
    groupadd soffid
fi

if ! getent passwd soffid >/dev/null 2>&1; then
    adduser --system --gid soffid --no-create-home --home-dir /opt/soffid soffid
fi
chown -R soffid:soffid /opt/soffid/iam-console-3

# This will only remove masks created by d-s-h on package removal.
systemctl enable 'soffid-iamconsole.service' || true 	
systemctl start soffid-iamconsole || true 

echo "Starting Soffid console. Please connect to http://localhost:8080 to configure"

%preun
#!/bin/sh
#!/bin/bash

systemctl stop 'soffid-iamconsole.service' || true

systemctl disable 'soffid-iamconsole.service' || true

%description


(Converted from a deb package by alien version 8.95.)

%files
"/lib/systemd/system/soffid-iamconsole.service"
%dir "/opt/soffid/iam-console-3/"
"/opt/soffid/iam-console-3/LICENSE"
"/opt/soffid/iam-console-3/NOTICE"
"/opt/soffid/iam-console-3/RELEASE-NOTES"
"/opt/soffid/iam-console-3/RUNNING.txt"
"/opt/soffid/iam-console-3/TOMEE-LICENSE"
%dir "/opt/soffid/iam-console-3/apps/"
"/opt/soffid/iam-console-3/apps/deployer.jar"
%dir "/opt/soffid/iam-console-3/bin/"
"/opt/soffid/iam-console-3/bin/TomEE.amd64.exe"
"/opt/soffid/iam-console-3/bin/TomEE.exe"
"/opt/soffid/iam-console-3/bin/TomEE.x86.exe"
"/opt/soffid/iam-console-3/bin/bootstrap.jar"
"/opt/soffid/iam-console-3/bin/catalina.bat"
"/opt/soffid/iam-console-3/bin/catalina.sh"
"/opt/soffid/iam-console-3/bin/commons-daemon-native.tar.gz"
"/opt/soffid/iam-console-3/bin/commons-daemon.jar"
%config "/opt/soffid/iam-console-3/bin/env.sh"
"/opt/soffid/iam-console-3/bin/service.bat"
"/opt/soffid/iam-console-3/bin/service.install.as.admin.bat"
"/opt/soffid/iam-console-3/bin/service.readme.txt"
"/opt/soffid/iam-console-3/bin/service.remove.as.admin.bat"
"/opt/soffid/iam-console-3/bin/setclasspath.bat"
"/opt/soffid/iam-console-3/bin/setclasspath.sh"
"/opt/soffid/iam-console-3/bin/soffid.ico"
"/opt/soffid/iam-console-3/bin/tomcat-juli.jar"
"/opt/soffid/iam-console-3/bin/tomcat-native.tar.gz"
%dir "/opt/soffid/iam-console-3/conf/"
"/opt/soffid/iam-console-3/conf/catalina.policy"
"/opt/soffid/iam-console-3/conf/catalina.properties"
%dir "/opt/soffid/iam-console-3/conf/conf.d/"
"/opt/soffid/iam-console-3/conf/conf.d/cxf-rs.properties"
"/opt/soffid/iam-console-3/conf/conf.d/cxf.properties"
"/opt/soffid/iam-console-3/conf/conf.d/hsql.properties"
"/opt/soffid/iam-console-3/conf/context.xml"
"/opt/soffid/iam-console-3/conf/jaspic-providers.xml"
"/opt/soffid/iam-console-3/conf/jaspic-providers.xsd"
"/opt/soffid/iam-console-3/conf/logging.properties"
%config "/opt/soffid/iam-console-3/conf/server.xml"
"/opt/soffid/iam-console-3/conf/system.properties.template"
"/opt/soffid/iam-console-3/conf/tomcat-users.xml"
"/opt/soffid/iam-console-3/conf/tomcat-users.xsd"
%config "/opt/soffid/iam-console-3/conf/tomee.xml"
"/opt/soffid/iam-console-3/conf/web.xml"
%dir "/opt/soffid/iam-console-3/lib/"
"/opt/soffid/iam-console-3/lib/FastInfoset-1.2.16.jar"
"/opt/soffid/iam-console-3/lib/activemq-broker-5.15.12.jar"
"/opt/soffid/iam-console-3/lib/activemq-client-5.15.12.jar"
"/opt/soffid/iam-console-3/lib/activemq-jdbc-store-5.15.12.jar"
"/opt/soffid/iam-console-3/lib/activemq-kahadb-store-5.15.12.jar"
"/opt/soffid/iam-console-3/lib/activemq-openwire-legacy-5.15.12.jar"
"/opt/soffid/iam-console-3/lib/activemq-protobuf-1.1.jar"
"/opt/soffid/iam-console-3/lib/activemq-ra-5.15.12.jar"
"/opt/soffid/iam-console-3/lib/batchee-jbatch-0.5-incubating.jar"
"/opt/soffid/iam-console-3/lib/bcprov-jdk15on-1.64.jar"
"/opt/soffid/iam-console-3/lib/bval-jsr-2.0.3.jar"
"/opt/soffid/iam-console-3/lib/catalina-ant.jar"
"/opt/soffid/iam-console-3/lib/catalina-ha.jar"
"/opt/soffid/iam-console-3/lib/catalina-ssi.jar"
"/opt/soffid/iam-console-3/lib/catalina-storeconfig.jar"
"/opt/soffid/iam-console-3/lib/catalina-tribes.jar"
"/opt/soffid/iam-console-3/lib/catalina.jar"
"/opt/soffid/iam-console-3/lib/commons-beanutils-1.9.4.jar"
"/opt/soffid/iam-console-3/lib/commons-cli-1.4.jar"
"/opt/soffid/iam-console-3/lib/commons-codec-1.14.jar"
"/opt/soffid/iam-console-3/lib/commons-collections-3.2.2.jar"
"/opt/soffid/iam-console-3/lib/commons-collections4-4.3.jar"
"/opt/soffid/iam-console-3/lib/commons-dbcp2-2.1.jar"
"/opt/soffid/iam-console-3/lib/commons-digester-1.8.jar"
"/opt/soffid/iam-console-3/lib/commons-jcs-core-2.1.jar"
"/opt/soffid/iam-console-3/lib/commons-jcs-jcache-2.1.jar"
"/opt/soffid/iam-console-3/lib/commons-lang3-3.8.1.jar"
"/opt/soffid/iam-console-3/lib/commons-logging-1.2.jar"
"/opt/soffid/iam-console-3/lib/commons-pool2-2.3.jar"
"/opt/soffid/iam-console-3/lib/cryptacular-1.2.4.jar"
"/opt/soffid/iam-console-3/lib/cxf-core-3.3.6.jar"
"/opt/soffid/iam-console-3/lib/cxf-rt-bindings-soap-3.3.6.jar"
"/opt/soffid/iam-console-3/lib/cxf-rt-bindings-xml-3.3.6.jar"
"/opt/soffid/iam-console-3/lib/cxf-rt-databinding-jaxb-3.3.6.jar"
"/opt/soffid/iam-console-3/lib/cxf-rt-frontend-jaxrs-3.3.6.jar"
"/opt/soffid/iam-console-3/lib/cxf-rt-frontend-jaxws-3.3.6.jar"
"/opt/soffid/iam-console-3/lib/cxf-rt-frontend-simple-3.3.6.jar"
"/opt/soffid/iam-console-3/lib/cxf-rt-management-3.3.6.jar"
"/opt/soffid/iam-console-3/lib/cxf-rt-rs-client-3.3.6.jar"
"/opt/soffid/iam-console-3/lib/cxf-rt-rs-extension-providers-3.3.6.jar"
"/opt/soffid/iam-console-3/lib/cxf-rt-rs-extension-search-3.3.6.jar"
"/opt/soffid/iam-console-3/lib/cxf-rt-rs-json-basic-3.3.6.jar"
"/opt/soffid/iam-console-3/lib/cxf-rt-rs-mp-client-3.3.6.jar"
"/opt/soffid/iam-console-3/lib/cxf-rt-rs-security-cors-3.3.6.jar"
"/opt/soffid/iam-console-3/lib/cxf-rt-rs-security-jose-3.3.6.jar"
"/opt/soffid/iam-console-3/lib/cxf-rt-rs-security-jose-jaxrs-3.3.6.jar"
"/opt/soffid/iam-console-3/lib/cxf-rt-rs-security-oauth2-3.3.6.jar"
"/opt/soffid/iam-console-3/lib/cxf-rt-rs-service-description-3.3.6.jar"
"/opt/soffid/iam-console-3/lib/cxf-rt-security-3.3.6.jar"
"/opt/soffid/iam-console-3/lib/cxf-rt-security-saml-3.3.6.jar"
"/opt/soffid/iam-console-3/lib/cxf-rt-transports-http-3.3.6.jar"
"/opt/soffid/iam-console-3/lib/cxf-rt-ws-addr-3.3.6.jar"
"/opt/soffid/iam-console-3/lib/cxf-rt-ws-policy-3.3.6.jar"
"/opt/soffid/iam-console-3/lib/cxf-rt-ws-security-3.3.6.jar"
"/opt/soffid/iam-console-3/lib/cxf-rt-wsdl-3.3.6.jar"
"/opt/soffid/iam-console-3/lib/ecj-4.15.jar"
"/opt/soffid/iam-console-3/lib/el-api.jar"
"/opt/soffid/iam-console-3/lib/geronimo-config-impl-1.2.1.jar"
"/opt/soffid/iam-console-3/lib/geronimo-connector-3.1.4.jar"
"/opt/soffid/iam-console-3/lib/geronimo-health-1.0.1.jar"
"/opt/soffid/iam-console-3/lib/geronimo-health-common-1.0.1.jar"
"/opt/soffid/iam-console-3/lib/geronimo-javamail_1.4_mail-1.9.0-alpha-2.jar"
"/opt/soffid/iam-console-3/lib/geronimo-metrics-1.0.2.jar"
"/opt/soffid/iam-console-3/lib/geronimo-metrics-common-1.0.2.jar"
"/opt/soffid/iam-console-3/lib/geronimo-openapi-impl-1.0.12.jar"
"/opt/soffid/iam-console-3/lib/geronimo-opentracing-1.0.0.jar"
"/opt/soffid/iam-console-3/lib/geronimo-transaction-3.1.4.jar"
"/opt/soffid/iam-console-3/lib/hawtbuf-1.11.jar"
"/opt/soffid/iam-console-3/lib/howl-1.0.1-1.jar"
"/opt/soffid/iam-console-3/lib/hsqldb-2.3.2.jar"
"/opt/soffid/iam-console-3/lib/iam-tomee.jar"
"/opt/soffid/iam-console-3/lib/istack-commons-runtime-3.0.8.jar"
"/opt/soffid/iam-console-3/lib/jackson-annotations-2.10.0.jar"
"/opt/soffid/iam-console-3/lib/jackson-core-2.10.0.jar"
"/opt/soffid/iam-console-3/lib/jackson-databind-2.10.0.jar"
"/opt/soffid/iam-console-3/lib/jackson-dataformat-yaml-2.10.0.jar"
"/opt/soffid/iam-console-3/lib/jakarta.activation-1.2.1.jar"
"/opt/soffid/iam-console-3/lib/jakarta.xml.bind-api-2.3.2.jar"
"/opt/soffid/iam-console-3/lib/jasper-el.jar"
"/opt/soffid/iam-console-3/lib/jasper.jar"
"/opt/soffid/iam-console-3/lib/jaspic-api.jar"
"/opt/soffid/iam-console-3/lib/jasypt-1.9.3.jar"
"/opt/soffid/iam-console-3/lib/java-support-7.3.0.jar"
"/opt/soffid/iam-console-3/lib/javaee-api-8.0-4.jar"
"/opt/soffid/iam-console-3/lib/jaxb-runtime-2.3.2.jar"
"/opt/soffid/iam-console-3/lib/joda-time-2.9.jar"
"/opt/soffid/iam-console-3/lib/johnzon-core-1.2.5.jar"
"/opt/soffid/iam-console-3/lib/johnzon-jaxrs-1.2.5.jar"
"/opt/soffid/iam-console-3/lib/johnzon-jsonb-1.2.5.jar"
"/opt/soffid/iam-console-3/lib/johnzon-mapper-1.2.5.jar"
"/opt/soffid/iam-console-3/lib/jose4j-0.6.0.jar"
"/opt/soffid/iam-console-3/lib/jsp-api.jar"
"/opt/soffid/iam-console-3/lib/mariadb-java-client.jar"
"/opt/soffid/iam-console-3/lib/mbean-annotation-api-8.0.4.jar"
"/opt/soffid/iam-console-3/lib/microprofile-config-api-1.3.jar"
"/opt/soffid/iam-console-3/lib/microprofile-fault-tolerance-api-1.1.4.jar"
"/opt/soffid/iam-console-3/lib/microprofile-health-api-1.0.jar"
"/opt/soffid/iam-console-3/lib/microprofile-jwt-auth-api-1.1.1.jar"
"/opt/soffid/iam-console-3/lib/microprofile-metrics-api-1.1.1.jar"
"/opt/soffid/iam-console-3/lib/microprofile-openapi-api-1.1.2.jar"
"/opt/soffid/iam-console-3/lib/microprofile-opentracing-api-1.1.2.jar"
"/opt/soffid/iam-console-3/lib/microprofile-rest-client-api-1.3.3.jar"
"/opt/soffid/iam-console-3/lib/mimepull-1.9.11.jar"
"/opt/soffid/iam-console-3/lib/mp-common-8.0.4.jar"
"/opt/soffid/iam-console-3/lib/mp-jwt-8.0.4.jar"
"/opt/soffid/iam-console-3/lib/myfaces-api-2.3.6.jar"
"/opt/soffid/iam-console-3/lib/myfaces-impl-2.3.6.jar"
"/opt/soffid/iam-console-3/lib/mysql-connector-java-5.1.21.jar"
"/opt/soffid/iam-console-3/lib/neethi-3.0.3.jar"
"/opt/soffid/iam-console-3/lib/ojdbc7.jar"
"/opt/soffid/iam-console-3/lib/openejb-api-8.0.4.jar"
"/opt/soffid/iam-console-3/lib/openejb-client-8.0.4.jar"
"/opt/soffid/iam-console-3/lib/openejb-core-8.0.4.jar"
"/opt/soffid/iam-console-3/lib/openejb-cxf-8.0.4.jar"
"/opt/soffid/iam-console-3/lib/openejb-cxf-rs-8.0.4.jar"
"/opt/soffid/iam-console-3/lib/openejb-cxf-transport-8.0.4.jar"
"/opt/soffid/iam-console-3/lib/openejb-ejbd-8.0.4.jar"
"/opt/soffid/iam-console-3/lib/openejb-hsql-8.0.4.jar"
"/opt/soffid/iam-console-3/lib/openejb-http-8.0.4.jar"
"/opt/soffid/iam-console-3/lib/openejb-javaagent.jar"
"/opt/soffid/iam-console-3/lib/openejb-jee-8.0.4.jar"
"/opt/soffid/iam-console-3/lib/openejb-jee-accessors-8.0.4.jar"
"/opt/soffid/iam-console-3/lib/openejb-jpa-integration-8.0.4.jar"
"/opt/soffid/iam-console-3/lib/openejb-loader-8.0.4.jar"
"/opt/soffid/iam-console-3/lib/openejb-rest-8.0.4.jar"
"/opt/soffid/iam-console-3/lib/openejb-server-8.0.4.jar"
"/opt/soffid/iam-console-3/lib/openejb-webservices-8.0.4.jar"
"/opt/soffid/iam-console-3/lib/openjpa-3.1.0.jar"
"/opt/soffid/iam-console-3/lib/opentracing-api-0.31.0.jar"
"/opt/soffid/iam-console-3/lib/openwebbeans-ee-2.0.12.jar"
"/opt/soffid/iam-console-3/lib/openwebbeans-ee-common-2.0.12.jar"
"/opt/soffid/iam-console-3/lib/openwebbeans-ejb-2.0.12.jar"
"/opt/soffid/iam-console-3/lib/openwebbeans-el22-2.0.12.jar"
"/opt/soffid/iam-console-3/lib/openwebbeans-impl-2.0.12.jar"
"/opt/soffid/iam-console-3/lib/openwebbeans-jsf-2.0.12.jar"
"/opt/soffid/iam-console-3/lib/openwebbeans-spi-2.0.12.jar"
"/opt/soffid/iam-console-3/lib/openwebbeans-web-2.0.12.jar"
"/opt/soffid/iam-console-3/lib/org.osgi.annotation.versioning-1.0.0.jar"
"/opt/soffid/iam-console-3/lib/postgresql.jar"
"/opt/soffid/iam-console-3/lib/quartz-openejb-shade-2.2.1.jar"
"/opt/soffid/iam-console-3/lib/saaj-impl-1.5.1.jar"
"/opt/soffid/iam-console-3/lib/safeguard-impl-1.2.1.jar"
"/opt/soffid/iam-console-3/lib/serp-1.15.1.jar"
"/opt/soffid/iam-console-3/lib/servlet-api.jar"
"/opt/soffid/iam-console-3/lib/slf4j-api-1.7.21.jar"
"/opt/soffid/iam-console-3/lib/slf4j-jdk14-1.7.21.jar"
"/opt/soffid/iam-console-3/lib/snakeyaml-1.24.jar"
"/opt/soffid/iam-console-3/lib/sqljdbc4.jar"
"/opt/soffid/iam-console-3/lib/stax-ex-1.8.1.jar"
"/opt/soffid/iam-console-3/lib/stax2-api-3.1.4.jar"
"/opt/soffid/iam-console-3/lib/swizzle-stream-1.6.2.jar"
"/opt/soffid/iam-console-3/lib/sxc-jaxb-core-0.8.jar"
"/opt/soffid/iam-console-3/lib/sxc-runtime-0.8.jar"
"/opt/soffid/iam-console-3/lib/taglibs-standard-impl-1.2.5.jar"
"/opt/soffid/iam-console-3/lib/taglibs-standard-jstlel-1.2.5.jar"
"/opt/soffid/iam-console-3/lib/taglibs-standard-spec-1.2.5.jar"
"/opt/soffid/iam-console-3/lib/tomcat-api.jar"
"/opt/soffid/iam-console-3/lib/tomcat-coyote.jar"
"/opt/soffid/iam-console-3/lib/tomcat-dbcp.jar"
"/opt/soffid/iam-console-3/lib/tomcat-i18n-cs.jar"
"/opt/soffid/iam-console-3/lib/tomcat-i18n-de.jar"
"/opt/soffid/iam-console-3/lib/tomcat-i18n-es.jar"
"/opt/soffid/iam-console-3/lib/tomcat-i18n-fr.jar"
"/opt/soffid/iam-console-3/lib/tomcat-i18n-ja.jar"
"/opt/soffid/iam-console-3/lib/tomcat-i18n-ko.jar"
"/opt/soffid/iam-console-3/lib/tomcat-i18n-pt-BR.jar"
"/opt/soffid/iam-console-3/lib/tomcat-i18n-ru.jar"
"/opt/soffid/iam-console-3/lib/tomcat-i18n-zh-CN.jar"
"/opt/soffid/iam-console-3/lib/tomcat-jdbc.jar"
"/opt/soffid/iam-console-3/lib/tomcat-jni.jar"
"/opt/soffid/iam-console-3/lib/tomcat-util-scan.jar"
"/opt/soffid/iam-console-3/lib/tomcat-util.jar"
"/opt/soffid/iam-console-3/lib/tomcat-websocket.jar"
"/opt/soffid/iam-console-3/lib/tomee-catalina-8.0.4.jar"
"/opt/soffid/iam-console-3/lib/tomee-common-8.0.4.jar"
"/opt/soffid/iam-console-3/lib/tomee-config-8.0.4.jar"
"/opt/soffid/iam-console-3/lib/tomee-jaxrs-8.0.4.jar"
"/opt/soffid/iam-console-3/lib/tomee-jdbc-8.0.4.jar"
"/opt/soffid/iam-console-3/lib/tomee-loader-8.0.4.jar"
"/opt/soffid/iam-console-3/lib/tomee-mojarra-8.0.4.jar"
"/opt/soffid/iam-console-3/lib/tomee-myfaces-8.0.4.jar"
"/opt/soffid/iam-console-3/lib/tomee-webapp-8.0.4.jar"
"/opt/soffid/iam-console-3/lib/tomee-webservices-8.0.4.jar"
"/opt/soffid/iam-console-3/lib/txw2-2.3.2.jar"
"/opt/soffid/iam-console-3/lib/websocket-api.jar"
"/opt/soffid/iam-console-3/lib/woodstox-core-5.0.3.jar"
"/opt/soffid/iam-console-3/lib/wsdl4j-1.6.3.jar"
"/opt/soffid/iam-console-3/lib/wss4j-bindings-2.2.5.jar"
"/opt/soffid/iam-console-3/lib/wss4j-policy-2.2.5.jar"
"/opt/soffid/iam-console-3/lib/wss4j-ws-security-common-2.2.5.jar"
"/opt/soffid/iam-console-3/lib/wss4j-ws-security-dom-2.2.5.jar"
"/opt/soffid/iam-console-3/lib/wss4j-ws-security-policy-stax-2.2.5.jar"
"/opt/soffid/iam-console-3/lib/wss4j-ws-security-stax-2.2.5.jar"
"/opt/soffid/iam-console-3/lib/xbean-asm7-shaded-4.14.jar"
"/opt/soffid/iam-console-3/lib/xbean-bundleutils-4.14.jar"
"/opt/soffid/iam-console-3/lib/xbean-finder-shaded-4.14.jar"
"/opt/soffid/iam-console-3/lib/xbean-naming-4.14.jar"
"/opt/soffid/iam-console-3/lib/xbean-reflect-4.14.jar"
"/opt/soffid/iam-console-3/lib/xml-resolver-1.2.jar"
"/opt/soffid/iam-console-3/lib/xmlschema-core-2.2.5.jar"
"/opt/soffid/iam-console-3/lib/xmlsec-2.1.4.jar"
%dir "/opt/soffid/iam-console-3/logs/"
"/opt/soffid/iam-console-3/logs/.placeholder"
%dir "/opt/soffid/iam-console-3/soffid/"
%dir "/opt/soffid/iam-console-3/soffid/bpm/"
"/opt/soffid/iam-console-3/soffid/bpm/add-agent-wf.par"
"/opt/soffid/iam-console-3/soffid/bpm/privileged-account-approval-2.0.0.par"
"/opt/soffid/iam-console-3/soffid/bpm/reconcile-process-wf-2.0.0.par"
"/opt/soffid/iam-console-3/soffid/failed.ear"
"/opt/soffid/iam-console-3/soffid/iam-ear.ear"
%dir "/opt/soffid/iam-console-3/soffid/plugins/"
"/opt/soffid/iam-console-3/soffid/plugins/sso-plugin.jar"
"/opt/soffid/iam-console-3/soffid/starting.ear"
%dir "/opt/soffid/iam-console-3/temp/"
%dir "/opt/soffid/iam-console-3/webapps/"
"/opt/soffid/iam-console-3/webapps/ROOT.war"
