package es.caib.bpm.exception;

public class BPMErrorCodes {

	/** ERROR CODE PARA INDICAR QUE LA TAREA YA SE ENCUENTRA ASIGNADA */
	public static int TAREA_YA_ASIGNADA_DIRECTAMENTE= 1000;
	/** ERROR CODE PARA INDICAR QUE EL ACTOR NO POSEE GRUPOS */
	public static int ACTOR_NO_POSEE_GRUPOS= 1001;
	/** ERROR CODE PARA INDICAR QUE EL PARAMETRO RECIBIDO ES INVALIDO */
	public static int PARAMETRO_INVALIDO= 2000;
	/** ERROR CODE PARA INDICAR QUE UN PROBLEMA DE ENTRADA/SALIDA */
	public static int ERROR_ENTRADA_SALIDA= 3000;  
	/** ERROR CODE PARA INDICAR QUE HUBO UN PROBLEMA DESPLEGANDO LA DEFINICION DE PROCESO */
	public static int ERROR_DESPLIEGUE_PROCESO= 3001;  
	
	/** ERROR CODE PARA INDICAR UN ERROR ESMASCARADO */
	public static int ERROR_ENMASCARADO= 9000;
	
	/** ERROR CODE PARA INDICAR UNA CONFIGURACION INVALIDA DE UNO DE LOS SERVICIOS */
	public static int CONFIGURACION_INVALIDA= 9999;
}
