// license-header java merge-point
//
// Attention: Generated code! Do not modify by hand!
// Generated by: SpringServiceLocator.vsl in andromda-spring-cartridge.
//
package es.caib.bpm.config;

/**
 * Locates and provides all available application services.
 */
public class BpmServiceLocator
{

    private BpmServiceLocator()
    {
        // shouldn't be instantiated
    }

    /**
     * The shared instance of this ServiceLocator.
     */
    private final static BpmServiceLocator instance = new BpmServiceLocator();

    /**
     * Gets the shared instance of this Class
     *
     * @return the shared service locator instance.
     */
    public static final BpmServiceLocator instance()
    {
        return instance;
    }

    /**
     * The bean factory reference instance.
     */
    private org.springframework.beans.factory.access.BeanFactoryReference beanFactoryReference;
    
    /**
     * The bean factory reference location.
     */
    private String beanFactoryReferenceLocation;
    
    /**
     * The bean factory reference id.
     */
    private String beanRefFactoryReferenceId;

    /**
     * Initializes the Spring application context from
     * the given <code>beanFactoryReferenceLocation</code>.  If <code>null</code>
     * is specified for the <code>beanFactoryReferenceLocation</code>
     * then the default application context will be used.
     *
     * @param beanFactoryReferenceLocation the location of the beanRefFactory reference.
     */
    public synchronized void init(final String beanFactoryReferenceLocation, final String beanRefFactoryReferenceId)
    {
        this.beanFactoryReferenceLocation = beanFactoryReferenceLocation;
        this.beanRefFactoryReferenceId = beanRefFactoryReferenceId;
        this.beanFactoryReference = null;
    }

    /**
     * Initializes the Spring application context from
     * the given <code>beanFactoryReferenceLocation</code>.  If <code>null</code>
     * is specified for the <code>beanFactoryReferenceLocation</code>
     * then the default application context will be used.
     *
     * @param beanFactoryReferenceLocation the location of the beanRefFactory reference.
     */
    public synchronized void init(final String beanFactoryReferenceLocation)
    {
        this.beanFactoryReferenceLocation = beanFactoryReferenceLocation;
        this.beanFactoryReference = null;
    }
    
   /**
     * The default bean reference factory location.
     */
    private final String DEFAULT_BEAN_REFERENCE_LOCATION = "beanRefFactory.xml";
    
    /**
     * The default bean reference factory ID.
     */
    private final String DEFAULT_BEAN_REFERENCE_ID = "beanRefFactory";

    /**
     * Gets the Spring ApplicationContext.
     */
    protected synchronized org.springframework.context.ApplicationContext getContext()
    {
        if (this.beanFactoryReference == null)
        {
            if (this.beanFactoryReferenceLocation == null)
            {
                this.beanFactoryReferenceLocation = DEFAULT_BEAN_REFERENCE_LOCATION;
            }
            if (this.beanRefFactoryReferenceId == null)
            {
                this.beanRefFactoryReferenceId = DEFAULT_BEAN_REFERENCE_ID;
            }
            org.springframework.beans.factory.access.BeanFactoryLocator beanFactoryLocator =
                org.springframework.context.access.ContextSingletonBeanFactoryLocator.getInstance(
                    this.beanFactoryReferenceLocation);
            this.beanFactoryReference = beanFactoryLocator.useBeanFactory(this.beanRefFactoryReferenceId);
        }
        return (org.springframework.context.ApplicationContext)this.beanFactoryReference.getFactory();
    }

    /**
     * Shuts down the ServiceLocator and releases any used resources.
     */
    public synchronized void shutdown()
    {
        if (this.beanFactoryReference != null)
        {
            this.beanFactoryReference.release();
            this.beanFactoryReference = null;
        }
    }

    /**
     * Gets an instance of {@link es.caib.seycon.ng.servei.AplicacioService}.
     */
    public final es.caib.seycon.ng.servei.AplicacioService getAplicacioService()
    {
        return (es.caib.seycon.ng.servei.AplicacioService)
            getContext().getBean("aplicacioService");
    }

    /**
     * Gets an instance of {@link es.caib.seycon.ng.servei.XarxaService}.
     */
    public final es.caib.seycon.ng.servei.XarxaService getXarxaService()
    {
        return (es.caib.seycon.ng.servei.XarxaService)
            getContext().getBean("xarxaService");
    }

    /**
     * Gets an instance of {@link es.caib.seycon.ng.servei.ImpressoraService}.
     */
    public final es.caib.seycon.ng.servei.ImpressoraService getImpressoraService()
    {
        return (es.caib.seycon.ng.servei.ImpressoraService)
            getContext().getBean("impressoraService");
    }

    /**
     * Gets an instance of {@link es.caib.seycon.ng.servei.GrupService}.
     */
    public final es.caib.seycon.ng.servei.GrupService getGrupService()
    {
        return (es.caib.seycon.ng.servei.GrupService)
            getContext().getBean("grupService");
    }

    /**
     * Gets an instance of {@link es.caib.seycon.ng.servei.LopdService}.
     */
    public final es.caib.seycon.ng.servei.LopdService getLopdService()
    {
        return (es.caib.seycon.ng.servei.LopdService)
            getContext().getBean("lopdService");
    }

    /**
     * Gets an instance of {@link es.caib.seycon.ng.servei.LlistesDeCorreuService}.
     */
    public final es.caib.seycon.ng.servei.LlistesDeCorreuService getLlistesDeCorreuService()
    {
        return (es.caib.seycon.ng.servei.LlistesDeCorreuService)
            getContext().getBean("llistesDeCorreuService");
    }

    /**
     * Gets an instance of {@link es.caib.seycon.ng.servei.UsuariService}.
     */
    public final es.caib.seycon.ng.servei.UsuariService getUsuariService()
    {
        return (es.caib.seycon.ng.servei.UsuariService)
            getContext().getBean("usuariService");
    }

    /**
     * Gets an instance of {@link es.caib.seycon.ng.servei.ConfiguracioService}.
     */
    public final es.caib.seycon.ng.servei.ConfiguracioService getConfiguracioService()
    {
        return (es.caib.seycon.ng.servei.ConfiguracioService)
            getContext().getBean("configuracioService");
    }

    /**
     * Gets an instance of {@link es.caib.seycon.ng.servei.workflow.AltaBaixaUsuariService}.
     */
    public final es.caib.seycon.ng.servei.workflow.AltaBaixaUsuariService getAltaBaixaUsuariService()
    {
        return (es.caib.seycon.ng.servei.workflow.AltaBaixaUsuariService)
            getContext().getBean("altaBaixaUsuariService");
    }

    /**
     * Gets an instance of {@link es.caib.seycon.ng.servei.workflow.ServidorsService}.
     */
    public final es.caib.seycon.ng.servei.workflow.ServidorsService getServidorsService()
    {
        return (es.caib.seycon.ng.servei.workflow.ServidorsService)
            getContext().getBean("servidorsService");
    }

    /**
     * Gets an instance of {@link es.caib.seycon.ng.servei.workflow.InformacioAutoritzacioService}.
     */
    public final es.caib.seycon.ng.servei.workflow.InformacioAutoritzacioService getInformacioAutoritzacioService()
    {
        return (es.caib.seycon.ng.servei.workflow.InformacioAutoritzacioService)
            getContext().getBean("informacioAutoritzacioService");
    }

    /**
     * Gets an instance of {@link es.caib.seycon.ng.servei.ServeiService}.
     */
    public final es.caib.seycon.ng.servei.ServeiService getServeiService()
    {
        return (es.caib.seycon.ng.servei.ServeiService)
            getContext().getBean("serveiService");
    }

    /**
     * Gets an instance of {@link es.caib.seycon.ng.servei.DadesAddicionalsService}.
     */
    public final es.caib.seycon.ng.servei.DadesAddicionalsService getDadesAddicionalsService()
    {
        return (es.caib.seycon.ng.servei.DadesAddicionalsService)
            getContext().getBean("dadesAddicionalsService");
    }

    /**
     * Gets an instance of {@link es.caib.seycon.ng.servei.AuditoriaService}.
     */
    public final es.caib.seycon.ng.servei.AuditoriaService getAuditoriaService()
    {
        return (es.caib.seycon.ng.servei.AuditoriaService)
            getContext().getBean("auditoriaService");
    }

    /**
     * Gets an instance of {@link es.caib.seycon.ng.servei.DispatcherService}.
     */
    public final es.caib.seycon.ng.servei.DispatcherService getDispatcherService()
    {
        return (es.caib.seycon.ng.servei.DispatcherService)
            getContext().getBean("dispatcherService");
    }

    /**
     * Gets an instance of {@link es.caib.seycon.ng.servei.DominiService}.
     */
    public final es.caib.seycon.ng.servei.DominiService getDominiService()
    {
        return (es.caib.seycon.ng.servei.DominiService)
            getContext().getBean("dominiService");
    }

    /**
     * Gets an instance of {@link es.caib.seycon.ng.servei.RegistreAccesService}.
     */
    public final es.caib.seycon.ng.servei.RegistreAccesService getRegistreAccesService()
    {
        return (es.caib.seycon.ng.servei.RegistreAccesService)
            getContext().getBean("registreAccesService");
    }

    /**
     * Gets an instance of {@link es.caib.seycon.ng.servei.AutoEnrollmentService}.
     */
    public final es.caib.seycon.ng.servei.AutoEnrollmentService getAutoEnrollmentService()
    {
        return (es.caib.seycon.ng.servei.AutoEnrollmentService)
            getContext().getBean("autoEnrollmentService");
    }

    /**
     * Gets an instance of {@link es.caib.seycon.ng.servei.TipusUnitatOrganitzativaService}.
     */
    public final es.caib.seycon.ng.servei.TipusUnitatOrganitzativaService getTipusUnitatOrganitzativaService()
    {
        return (es.caib.seycon.ng.servei.TipusUnitatOrganitzativaService)
            getContext().getBean("tipusUnitatOrganitzativaService");
    }

    /**
     * Gets an instance of {@link es.caib.seycon.ng.servei.PuntEntradaService}.
     */
    public final es.caib.seycon.ng.servei.PuntEntradaService getPuntEntradaService()
    {
        return (es.caib.seycon.ng.servei.PuntEntradaService)
            getContext().getBean("puntEntradaService");
    }

    /**
     * Gets an instance of {@link es.caib.seycon.ng.servei.XestibService}.
     */
    public final es.caib.seycon.ng.servei.XestibService getXestibService()
    {
        return (es.caib.seycon.ng.servei.XestibService)
            getContext().getBean("xestibService");
    }

    /**
     * Gets an instance of {@link es.caib.seycon.ng.servei.AutoritzacioService}.
     */
    public final es.caib.seycon.ng.servei.AutoritzacioService getAutoritzacioService()
    {
        return (es.caib.seycon.ng.servei.AutoritzacioService)
            getContext().getBean("autoritzacioService");
    }

    /**
     * Gets an instance of {@link es.caib.seycon.ng.servei.SeyconServerService}.
     */
    public final es.caib.seycon.ng.servei.SeyconServerService getSeyconServerService()
    {
        return (es.caib.seycon.ng.servei.SeyconServerService)
            getContext().getBean("seyconServerService");
    }

    /**
     * Gets an instance of {@link es.caib.seycon.ng.servei.ServerPluginService}.
     */
    public final es.caib.seycon.ng.servei.ServerPluginService getServerPluginService()
    {
        return (es.caib.seycon.ng.servei.ServerPluginService)
            getContext().getBean("serverPluginService");
    }

    /**
     * Gets an instance of {@link es.caib.seycon.ng.servei.FederacioService}.
     */
    public final es.caib.seycon.ng.servei.FederacioService getFederacioService()
    {
        return (es.caib.seycon.ng.servei.FederacioService)
            getContext().getBean("federacioService");
    }

    /**
     * Gets an instance of {@link es.caib.seycon.ng.servei.DominiUsuariService}.
     */
    public final es.caib.seycon.ng.servei.DominiUsuariService getDominiUsuariService()
    {
        return (es.caib.seycon.ng.servei.DominiUsuariService)
            getContext().getBean("dominiUsuariService");
    }

    /**
     * Gets an instance of {@link es.caib.seycon.ng.servei.PasswordService}.
     */
    public final es.caib.seycon.ng.servei.PasswordService getPasswordService()
    {
        return (es.caib.seycon.ng.servei.PasswordService)
            getContext().getBean("passwordService");
    }

    /**
     * Gets an instance of {@link es.caib.seycon.ng.servei.SessioService}.
     */
    public final es.caib.seycon.ng.servei.SessioService getSessioService()
    {
        return (es.caib.seycon.ng.servei.SessioService)
            getContext().getBean("sessioService");
    }

    /**
     * Gets an instance of {@link es.caib.seycon.ng.webservice.XestibDocentService}.
     */
    public final es.caib.seycon.ng.webservice.XestibDocentService getXestibDocentService()
    {
        return (es.caib.seycon.ng.webservice.XestibDocentService)
            getContext().getBean("xestibDocentService");
    }


    /**
     * Gets an instance of {@link es.caib.seycon.ng.sync.servei.SecretStoreService}.
     */
    public final es.caib.seycon.ng.sync.servei.SecretStoreService getSecretStoreService()
    {
        return (es.caib.seycon.ng.sync.servei.SecretStoreService)
            getContext().getBean("secretStoreService");
    }

    /**
     * Gets an instance of {@link es.caib.seycon.ng.sync.servei.ServerService}.
     */
    public final es.caib.seycon.ng.sync.servei.ServerService getServerService()
    {
        return (es.caib.seycon.ng.sync.servei.ServerService)
            getContext().getBean("serverService");
    }

    /**
     * Gets an instance of {@link es.caib.seycon.ng.sync.servei.LogonService}.
     */
    public final es.caib.seycon.ng.sync.servei.LogonService getLogonService()
    {
        return (es.caib.seycon.ng.sync.servei.LogonService)
            getContext().getBean("logonService");
    }

    /**
     * Gets an instance of {@link es.caib.seycon.ng.sync.servei.SyncStatusService}.
     */
    public final es.caib.seycon.ng.sync.servei.SyncStatusService getSyncStatusService()
    {
        return (es.caib.seycon.ng.sync.servei.SyncStatusService)
            getContext().getBean("syncStatusService");
    }

    /**
     * Gets an instance of {@link es.caib.seycon.ng.sync.servei.CertificateEnrollService}.
     */
    public final es.caib.seycon.ng.sync.servei.CertificateEnrollService getCertificateEnrollService()
    {
        return (es.caib.seycon.ng.sync.servei.CertificateEnrollService)
            getContext().getBean("certificateEnrollService");
    }

    /**
     * Gets an instance of {@link es.caib.seycon.ng.sync.agent.AgentManager}.
     */
    public final es.caib.seycon.ng.sync.agent.AgentManager getAgentManager()
    {
        return (es.caib.seycon.ng.sync.agent.AgentManager)
            getContext().getBean("agentManager");
    }


    /**
     * Gets an instance of the given service.
     */
    public final Object getService(String serviceName)
    {
        return getContext().getBean(serviceName);
    }

}