package es.caib.seycon.ng.install;

import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileWriter;
import java.io.IOException;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.io.Reader;
import java.io.UnsupportedEncodingException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Properties;
import java.util.Random;

import javax.swing.JOptionPane;

import com.install4j.api.context.Context;
import com.install4j.api.context.ProgressInterface;
import com.install4j.api.screens.Screen;

public class NasConfigurator {
    Context ctx;
    
    private Statement stmt;

    public NasConfigurator(com.install4j.api.context.Context ctx) {
        this.ctx = ctx;
    }

    public void configure () throws IOException {
        File f = ctx.getInstallationDirectory();
        File props = new File (f, "jboss/server/default/conf/es/caib/bpm/nas/properties/nas-custom.properties"); //$NON-NLS-1$
        if (! props.canRead()) {
            Properties p = new Properties();
            p.put("signer.strategy","es.caib.bpm.nas.sign.CAIBStrategy"); //$NON-NLS-1$ //$NON-NLS-2$
            p.put("communication.strategy","es.caib.bpm.nas.comm.LocalFileSystemStrategy"); //$NON-NLS-1$ //$NON-NLS-2$
            p.put("rootPath", f.getAbsolutePath()+"/docs/data"); //$NON-NLS-1$ //$NON-NLS-2$
            p.put("tempPath", f.getAbsolutePath()+"/docs/tmp"); //$NON-NLS-1$ //$NON-NLS-2$
            props.getParentFile().mkdirs();
            p.store(new FileWriter(props), "Generated by installation wizard");  //$NON-NLS-1$
            
            new File (f, "/docs/data").mkdirs(); //$NON-NLS-1$
            new File (f, "/docs/tmp").mkdirs(); //$NON-NLS-1$
        }
        
    }

}
