package es.caib.seycon.ng.install;

import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.util.Enumeration;
import java.util.Properties;

import com.install4j.api.context.Context;

public class PropertiesStore {

    public static final String DB_STATUS = "dbStatus"; //$NON-NLS-1$

    private static String keys[] = { "dbDriver", "dbDriverString", "dbDriverUrl", "dbDriverClass", "dbSanitySelect", //$NON-NLS-1$ //$NON-NLS-2$ //$NON-NLS-3$ //$NON-NLS-4$ //$NON-NLS-5$
            "dbPort", "dbTableTablespaceSize", "dbIndexTablespaceSize", "hostName", "domainName", //$NON-NLS-1$ //$NON-NLS-2$ //$NON-NLS-3$ //$NON-NLS-4$ //$NON-NLS-5$
            "dbUser", "dbHost", "dbSid", "dbSchema", "dbSchemaPassword", "dbVersion", //$NON-NLS-1$ //$NON-NLS-2$ //$NON-NLS-3$ //$NON-NLS-4$ //$NON-NLS-5$ //$NON-NLS-6$
            "dbTableTablespace", "dbIndexTablespace", "dbConnectionChecker", "dbExceptionSorter", DB_STATUS //$NON-NLS-1$ //$NON-NLS-2$ //$NON-NLS-3$ //$NON-NLS-4$

    };

    Context ctx; 

    public PropertiesStore(com.install4j.api.context.Context ctx) {
    			this.ctx = ctx;
    }

    public void load() {
        String s = ctx.getInstallationDirectory().getPath();
        s += "/jboss/server/default/conf/seu.properties"; //$NON-NLS-1$
        File configFile = new File(s);
        if (configFile.isFile() && configFile.canRead()) {
            Properties p = new Properties();
            try {
                p.load(new FileInputStream(configFile));
                Enumeration e = p.keys();
                while (e.hasMoreElements()) {
                    String key = (String) e.nextElement();
                    String v = p.getProperty(key);
                    if (key.startsWith("i.")) //$NON-NLS-1$
                        ctx.setVariable(key.substring(2), Integer.decode(v));
                    else if (key.startsWith("l.")) //$NON-NLS-1$
                        ctx.setVariable(key.substring(2), Long.decode(v));
                    else
                        ctx.setVariable(key, v);
                }
            } catch (Exception e1) {
                e1.printStackTrace();
            }
        }
    }

    public void save() {
        String s = ctx.getInstallationDirectory().getPath();
        s += "/jboss/server/default/conf/seu.properties"; //$NON-NLS-1$
        File configFile = new File(s);
        Properties p = new Properties();
        try {
            for (int i = 0; i < keys.length; i++) {
                Object value = ctx.getVariable(keys[i]);
                if (value != null) {
                    if (value instanceof Long)
                        p.setProperty("l." + keys[i], value.toString()); //$NON-NLS-1$
                    else if (value instanceof Integer)
                        p.setProperty("i." + keys[i], value.toString()); //$NON-NLS-1$
                    else
                        p.setProperty(keys[i], value.toString());
                }
            }
            p.store(new FileOutputStream(configFile), "Autogenerated by installer");  //$NON-NLS-1$
        } catch (Exception e1) {
            e1.printStackTrace();
        }
    }
}
