
ALTER TABLE SC_XARXES ADD XAR_DHCPSUP INTEGER;
ALTER TABLE SC_MAQUIN ADD MAQ_DYNIP INTEGER;
ALTER TABLE SC_MAQUIN ADD MAQ_LASTSEEN DATE;
ALTER TABLE SC_MAQUIN ADD MAQ_DELETED INTEGER;
ALTER TABLE SC_MAQUIN ADD MAQ_SERIAL VARCHAR2(200 CHAR);

MYSQL ALTER TABLE "SC_MAQUIN" ADD CONSTRAINT "MAQ_UK_SERIAL" UNIQUE ("MAQ_SERIAL") ENABLE;
ORACLE ALTER TABLE "SC_MAQUIN" ADD CONSTRAINT "MAQ_UK_SERIAL" UNIQUE ("MAQ_SERIAL") ENABLE;

--------------------------------------------------------
--  DDL for Index MAQ_UK_NOM
--------------------------------------------------------

CREATE UNIQUE INDEX "MAQ_SERIAL" ON "SC_MAQUIN" ("MAQ_SERIAL")
;
 
 

UPDATE SC_XARXES SET XAR_DHCPSUP=1;

UPDATE SC_MAQUIN SET MAQ_DYNIP = 0;

UPDATE SC_MAQUIN SET MAQ_DELETED = 0;

