


CREATE TABLE "SC_ACCACC" (
  AAC_ID  BIGIN NOT NULL AUTO_INCREMENT PRIMARY KEY,
  AAC_ROL_ID BIGINT,
  AAC_GRU_ID BIGINT,
  AAC_USU_ID BIGINT,
  AAC_ACC_ID BIGINT);

ALTER TABLE "SC_ACCACC" ADD CONSTRAINT "SC_ACCACC_AAC_ACC_ID" FOREIGN KEY ("AAC_ACC_ID")
	  REFERENCES "SC_ACCOUN" ("ACC_ID") ENABLE;

ALTER TABLE "SC_ACCACC" ADD CONSTRAINT "SC_ACCACC_AAC_GRU_ID" FOREIGN KEY ("AAC_GRU_ID")
	  REFERENCES "SC_GRUPS" ("GRU_ID") ENABLE;

ALTER TABLE "SC_ACCACC" ADD CONSTRAINT "SC_ACCACC_AAC_ROL_ID" FOREIGN KEY ("AAC_ROL_ID")
	  REFERENCES "SC_ROLES" ("ROL_ID") ENABLE;

ALTER TABLE "SC_ACCACC" ADD CONSTRAINT "SC_ACCACC_AAC_USU_ID" FOREIGN KEY ("AAC_USU_ID")
	  REFERENCES "SC_USUARI" ("USU_ID") ENABLE;


----------------------------------------
-- SC_ACCOUN (Accounts)
----------------------------------------

CREATE TABLE "SC_ACCOUN" (
  "ACC_ID" bigint(20) NOT NULL AUTO_INCREMENT PRIMARY KEY,
  "ACC_TYPE" VARCHAR2(1 CHAR) NOT NULL,
  "ACC_NAME" VARCHAR2(128 CHAR) DEFAULT NULL,
  "ACC_DIS_ID" BIGINT NOT NULL,
  "ACC_DESCRI" VARCHAR2(255 CHAR) DEFAULT NULL,
  "ACC_LASUPD" DATE,
  "ACC_LASPAS" DATE,
  "ACC_PASEXP" DATE,
  "ACC_SECRET" CLOB,
  "ACC_DISABL" SMALLINT,
  "ACC_TUS_ID" BIGIN 
);

ALTER TABLE "SC_ACCOUN" ADD CONSTRAINT "SC_ACCOUN_ACC_DIS_ID" FOREIGN KEY ("ACC_DIS_ID")
	  REFERENCES "SC_DISPAT" ("DIS_ID") ENABLE;

ALTER TABLE "SC_ACCOUN" ADD CONSTRAINT "SC_ACCOUN_ACC_TUS_ID" FOREIGN KEY ("ACC_TUS_ID")
	  REFERENCES "SC_TIPUSU" ("TUS_ID") ENABLE;

--------------------------------------
-- SC_ACCPWD (Account password)
--------------------------------------

CREATE TABLE "SC_ACCPWD" (
  "APW_ID" BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  "APW_PASSWD" VARCHAR2(255CHAR) NOT NULL,
  "APW_ORDER" BIGINT NOT NULL,
  "APW_DATE" DATE NOT NULL,
  "APW_EXPDAT" DATE NOT NULL,
  "APW_ACTIVE" VARCHAR2(255 CHAR) NOT NULL,
  "APW_ACC_ID" BIGINT NOT NULL
);

ALTER TABLE "SC_ACCPWD" ADD CONSTRAINT "SC_ACCPWD_APW_ACC_ID" FOREIGN KEY ("APW_ACC_ID")
	  REFERENCES "SC_ACCOUN" ("ACC_ID") ENABLE;



ALTER TABLE "SC_AUDITO" ADD "AUD_ACCOUN" VARCHAR2(128 CHAR);


ALTER TABLE "SC_CONTRA" DROP FOREIGN KEY "SC_CONTRA_UK" ;
-- DROP TABLE SC_CODUSU
ALTER TABLE "SC_DISPAT" ADD "DIS_DOU_ID" NUMBER(19,0) ;

ALTER TABLE "SC_DISPAT" ADD CONSTRAINT "SC_DISPAT_DIS_DOU_ID" FOREIGN KEY ("DIS_DOU_ID")
	  REFERENCES "SC_DOMUSU" ("DOU_ID") ENABLE;

ALTER TABLE "SC_DISPAT" ADD CONSTRAINT "SC_DISPAT_DIS_DCN_ID" FOREIGN KEY ("DIS_DCN_ID")
	  REFERENCES "SC_DOMCON" ("DCN_ID") ENABLE;

UPDATE SC_DISPAT SET DIS_DOU_ID = (SELECT DCN_DOU_ID FROM SC_DOMCON WHERE DCN_ID=DIS_DCN_ID);



