ALTER INDEX RAC_MAQ_FK_I rebuild;
ALTER INDEX RAC_MAQ_ORI rebuild;
ALTER INDEX RAC_SER_FK_I  rebuild;
ALTER INDEX RAC_USU_FK_I  rebuild;
ALTER INDEX RAC_AGE_DAT_I rebuild;
ALTER INDEX RAC_AGE_I  rebuild;