
--update
grant select, delete, update, insert on "SC_WL_LOGAUT" to www_seycon;
grant select, delete, update, insert on "SC_ROLFIT" to www_seycon;
grant select, delete, update, insert on "SC_FITXER" to www_seycon;
grant select, delete, update, insert on "SC_ROLES" to www_seycon;
grant select, delete, update, insert on "SC_ROLUSU" to www_seycon;
grant select, delete, update, insert on "SC_ROLPUE" to www_seycon;
grant select, delete, update, insert on "SC_REGCPD" to www_seycon;
grant select, delete, update, insert on "SC_EXTLCO" to www_seycon;
grant select, delete, update, insert on "SC_DOMCOR" to www_seycon;
grant select, delete, update, insert on "SC_DISPAT" to www_seycon;
grant select, delete, update, insert on "SC_DADUSU" to www_seycon;
grant select, delete, update, insert on "SC_CONTRA" to www_seycon;
grant select, delete, update, insert on "SC_CONTAR" to www_seycon;
grant select, delete, update, insert on "SC_FARREN" to www_seycon;
grant select, delete, update, insert on "SC_PETFAR" to www_seycon;
--grant select, delete, update, insert on "SC_WL_CERTIF" to www_seycon;
grant select, delete, update, insert on "SC_USUPUE" to www_seycon;
grant select, delete, update, insert on "SC_USULCO" to www_seycon;
grant select, delete, update, insert on "SC_USUIMP" to www_seycon;
grant select, delete, update, insert on "SC_USUGRU" to www_seycon;
grant select, delete, update, insert on "SC_CONFIG" to www_seycon;
grant select, delete, update, insert on "SC_AUTXAR" to www_seycon;
grant select, delete, update, insert on "SC_AUTSER" to www_seycon;
grant select, delete, update, insert on "SC_AUTCFG" to www_seycon;
grant select, delete, update, insert on "SC_AUDITO" to www_seycon;
grant select, delete, update, insert on "SC_APLICA" to www_seycon;
grant select, delete, update, insert on "SC_WL_USUGRU" to www_seycon;
grant select, delete, update, insert on "SC_WL_USUARI" to www_seycon;
grant select, delete, update, insert on "SC_XARXES" to www_seycon;
grant select, delete, update, insert on "SC_USUARI" to www_seycon;
--grant select, delete, update, insert on "SC_TMPUSU" to www_seycon;
grant select, delete, update, insert on "SC_TIPEXE" to www_seycon;
grant select, delete, update, insert on "SC_TIPDAD" to www_seycon;
grant select, delete, update, insert on "SC_TASQUE" to www_seycon;
grant select, delete, update, insert on "SC_TARGET" to www_seycon;
grant select, delete, update, insert on "SC_TARCPD" to www_seycon;
grant select, delete, update, insert on "SC_SSO" to www_seycon;
grant select, delete, update, insert on "SC_SESSIO" to www_seycon;
grant select, delete, update, insert on "SC_SERVEI" to www_seycon;
grant select, delete, update, insert on "SC_REGACC" to www_seycon;
grant select, delete, update, insert on "SC_PUNENT" to www_seycon;
grant select, delete, update, insert on "SC_PUEPUE" to www_seycon;
grant select, delete, update, insert on "SC_PORTS" to www_seycon;
grant select, delete, update, insert on "SC_PORCPD" to www_seycon;
grant select, delete, update, insert on "SC_POLUSU" to www_seycon;
grant select, delete, update, insert on "SC_POLITI" to www_seycon;
grant select, delete, update, insert on "SC_MAQUIN" to www_seycon;
grant select, delete, update, insert on "SC_LLICOR" to www_seycon;
grant select, delete, update, insert on "SC_LCOLCO" to www_seycon;
grant select, delete, update, insert on "SC_IMPRES" to www_seycon;
grant select, delete, update, insert on "SC_ICONES" to www_seycon;
grant select, delete, update, insert on "SC_GRUPUE" to www_seycon;
grant select, delete, update, insert on "SC_GRUPS" to www_seycon;
grant select, delete, update, insert on "SC_GRUIMP" to www_seycon;
grant select, delete, update, insert on "SC_EXEPUE" to www_seycon;
grant select, delete, update, insert on "SC_PETFAR" to www_seycon;
grant select, delete, update, insert on "SC_TIPUSUO" to www_seycon;
grant select, delete, update, insert on "SC_DOMAPP" to www_seycon;
grant select, delete, update, insert on "SC_ADMINAPP" to www_seycon;
grant select, delete, update, insert on "SC_RESP_SEG_ORG_USUARI" to www_seycon;
grant select, delete, update, insert on "SC_VALOR_DOMINI" to www_seycon;
grant select, delete, update, insert on "JBPM_TASK" to www_seycon;
grant select, delete, update, insert on "JBPM_VARIABLEINSTANCE" to www_seycon;
grant select, delete, update, insert on "JBPM_TOKEN" to www_seycon;
grant select, delete, update, insert on "JBPM_RUNTIMEACTION" to www_seycon;
grant select, delete, update, insert on "JBPM_MODULEINSTANCE" to www_seycon;
grant select, delete, update, insert on "BPM_DATABASE_PROPERTY" to www_seycon;
grant select, delete, update, insert on "JBPM_TRANSITION" to www_seycon;
grant select, delete, update, insert on "JBPM_ID_GROUP" to www_seycon;
grant select, delete, update, insert on "JBPM_DELEGATION" to www_seycon;
grant select, delete, update, insert on "JBPM_EXCEPTIONHANDLER" to www_seycon;
grant select, delete, update, insert on "JBPM_MESSAGE" to www_seycon;
grant select, delete, update, insert on "JBPM_PROCESSINSTANCE" to www_seycon;
grant select, delete, update, insert on "JBPM_SWIMLANE" to www_seycon;
grant select, delete, update, insert on "BPM_PROCESS_DEFINITION_ROLES" to www_seycon;
grant select, delete, update, insert on "BPM_USER_INTERFACE_CLASS" to www_seycon;
grant select, delete, update, insert on "BPM_PROC_DEF_PROPERTIES" to www_seycon;
grant select, delete, update, insert on "JBPM_DECISIONCONDITIONS" to www_seycon;
grant select, delete, update, insert on "JBPM_TIMER" to www_seycon;
grant select, delete, update, insert on "BPM_PROCESS_FILE" to www_seycon;
grant select, delete, update, insert on "JBPM_ID_MEMBERSHIP" to www_seycon;
grant select, delete, update, insert on "JBPM_TASKACTORPOOL" to www_seycon;
grant select, delete, update, insert on "JBPM_POOLEDACTOR" to www_seycon;
grant select, delete, update, insert on "JBPM_PROCESSDEFINITION" to www_seycon;
grant select, delete, update, insert on "JBPM_TASKCONTROLLER" to www_seycon;
grant select, delete, update, insert on "JBPM_ACTION" to www_seycon;
grant select, delete, update, insert on "JBPM_BYTEBLOCK" to www_seycon;
grant select, delete, update, insert on "JBPM_COMMENT" to www_seycon;
grant select, delete, update, insert on "JBPM_ID_USER" to www_seycon;
grant select, delete, update, insert on "JBPM_VARIABLEACCESS" to www_seycon;
grant select, delete, update, insert on "JBPM_LOG" to www_seycon;
grant select, delete, update, insert on "JBPM_TASKINSTANCE" to www_seycon;
grant select, delete, update, insert on "JBPM_NODE" to www_seycon;
grant select, delete, update, insert on "JBPM_TOKENVARIABLEMAP" to www_seycon;
grant select, delete, update, insert on "JBPM_MODULEDEFINITION" to www_seycon;
grant select, delete, update, insert on "JBPM_BYTEARRAY" to www_seycon;
grant select, delete, update, insert on "JBPM_EVENT" to www_seycon;
grant select, delete, update, insert on "JBPM_SWIMLANEINSTANCE" to www_seycon;
grant select, delete, update, insert on "BPM_USER_INTERFACE" to www_seycon;
grant select, delete, update, insert on "JBPM_ID_PERMISSIONS" to www_seycon;
grant select, delete, update, insert on "SC_ADMIN_SEG_ORG_USUARI" to www_seycon;

grant execute on "SC_UPDATE_USER" to www_seycon;
grant execute on "SC_ASIGNA_CONTRA" to www_seycon;
grant execute on "SC_CREAR_TARGETA" to www_seycon;
grant execute on "SC_ROLE_SUPERROLE_UPDATEABLE" to www_seycon;
grant execute on "SC_ROLE_UPDATEABLE" to www_seycon;

grant select on "BPM_SEQACC" to www_seycon;
grant select on "BPM_SEQDBP" to www_seycon;
grant select on "BPM_SEQDOC" to www_seycon;
grant select on "BPM_SEQFIL" to www_seycon;
grant select on "BPM_SEQPDP" to www_seycon;
grant select on "BPM_SEQPDR" to www_seycon;
grant select on "BPM_SEQPER" to www_seycon;
grant select on "BPM_SEQPRO" to www_seycon;
grant select on "BPM_SEQROL" to www_seycon;
grant select on "BPM_SEQSIG" to www_seycon;
grant select on "BPM_SEQUSC" to www_seycon;
grant select on "BPM_SEQUSI" to www_seycon;
grant select on "HIBERNATE_SEQUENCE" to www_seycon;
grant select on "SC_APL_SEQ" to www_seycon;
grant select on "SC_AUD_SEQ" to www_seycon;
grant select on "SC_AUS_SEQ" to www_seycon;
grant select on "SC_AXA_SEQ" to www_seycon;
grant select on "SC_CON_SEQ" to www_seycon;
grant select on "SC_CONTRA_SEQ" to www_seycon;
grant select on "SC_DCO_SEQ" to www_seycon;
grant select on "SC_DIS_SEQ" to www_seycon;
grant select on "SC_FAR_SEQ" to www_seycon;
grant select on "SC_GRU_SEQ" to www_seycon;
grant select on "SC_ICO_SEQ" to www_seycon;
grant select on "SC_IMP_SEQ" to www_seycon;
grant select on "SC_LCO_SEQ" to www_seycon;
grant select on "SC_MAQ_SEQ" to www_seycon;
grant select on "SC_PCP_SEQ" to www_seycon;
grant select on "SC_PFE_SEQ" to www_seycon;
grant select on "SC_POL_SEQ" to www_seycon;
grant select on "SC_POR_SEQ" to www_seycon;
grant select on "SC_PUE_SEQ" to www_seycon;
grant select on "SC_RAC_SEQ" to www_seycon;
grant select on "SC_ROL_SEQ" to www_seycon;
grant select on "SC_ROLES_SEQ" to www_seycon;
grant select on "SC_SEQFIT" to www_seycon;
grant select on "SC_SER_SEQ" to www_seycon;
grant select on "SC_SES_SEQ" to www_seycon;
grant select on "SC_SSO_SEQ" to www_seycon;
grant select on "SC_TAR_SEQ" to www_seycon;
grant select on "SC_TAS_SEQ" to www_seycon;
grant select on "SC_USU_SEQ" to www_seycon;
grant select on "SC_USUCODI_SEQ" to www_seycon;
grant select on "SC_XAR_SEQ" to www_seycon;
grant select on "SEQ_RECID" to www_seycon;

grant insert,update,select,delete on SC_ROLGRUP to www_seycon;