-- CREAMOS EL DBLINK A SEEDUC, como usuario DBA (system)
-- ¿ALGUNA FORMA DE HACERLO?
GRANT CREATE DATABASE LINK TO seycon; -- USUARIO DBA (SYSTEM)
CREATE DATABASE LINK "SEYCON.WORLD@SEEDUC"
 CONNECT TO SEEDUC
 IDENTIFIED BY SEEDUC
 USING 'SEYCON.WORLD';
--REVOKE CREATE DATABASE LINK TO seycon; -- USUARIO DBA (SYSTEM)


-- tablas que utilizan la secuencia de hibernate para generar el id (TODAS las anteriores)
SC_APLICA
SC_CONTRA
SC_DADUSU
SC_DISPAT
SC_DOMCOR
SC_GRUPS
SC_LLICOR
SC_MAQUIN
SC_ROLES
SC_ROLUSU
SC_USUARI
SC_USUGRU
SC_USULCO (sus 2 elementos son foreign key -- no tiene ID propia, son ambas)
SC_XARXES


-- INFORME DE DIFERENCIAS ENTRE TABLAS
SC_APLICA
		APL_ID: PK Insertar desde secuencia hibernate
		APL_CODI
		APL_NOM
		APL_DIRFON
		APL_DIRECT
		APL_BD
		APL_IDCONTACT: NUEVO. DUDA: ¿Corresponde con la columna de seeduc varchar2 APL_RESPON?
					   Es una FK a Usuari en seycon

SC_CONTRA
		CTR_IDUSU: FK a SC_USUARI
		CTR_ORDRE
		CTR_CONTRA
		CTR_ACTIU
		CTR_DATA
		CTR_DATCAD
		CTR_ID: Insertar desde secuencia hibernate (NUEVO)

SC_DADUSU
		DUS_ID: Insertar desde secuencia hibernate (NUEVO)
		DUS_IDUSU: FK a SC_USUARI
		DUS_VALOR
		DUS_TDAID: (NUEVO) Debe hacer referencia a SC_TIPDAD según el valor(cadena) de DUS_CODTDA
			DUDAS: Hay dos valores en la tabla: DNI, TARGETA RESSIDENT ¿existen en SC_TIPDAD? 
				  ¿el DNI, TARGETA RESIDENT se deben guardar como referencia a NIF?

SC_DISPAT
		DIS_ID: PK desde hibernate
		DIS_CODI
		DIS_NOMCLA
		DIS_URL
		DIS_PARAM0
		DIS_PARAM1
		DIS_PARAM2
		DIS_PARAM3
		DIS_PARAM4
		DIS_PARAM5
		DIS_PARAM6
		DIS_PARAM7
		DIS_PARAM8
		DIS_PARAM9
		DIS_BASROL
		DIS_SEGUR
		DIS_URL2: NUEVO
		DIS_TIPUSU: NUEVO
		DIS_GRUPS: NUEVO

SC_DOMCOR
		DCO_ID: autonumérico hibernate
		DCO_CODI
		DCO_DESCRI
		DCO_OBSOLET: NUEVO ¿Valor=N?
		
SC_GRUPS
		GRU_ID: autonumérico hibernate
		GRU_CODI
		GRU_DESCRI
		GRU_IDMAQ: FK a SC_MAQUIN
		GRU_QUOTA
		GRU_UNIOFI
		GRU_PARE: NUEVO
		GRU_TIPUS: NUEVO
		GRU_OBSOLET: NUEVO
		GRU_ORGANITZATIU: NUEVO
		GRU_ADMINISTRADOR: NUEVO

SC_LLICOR
		LCO_ID: Autonumérico hibernate
		LCO_DESCRI
		LCO_NOM
		LCO_IDDCO: FK A SC_DOMCOR

SC_MAQUIN
		MAQ_ID: Autonumérico Hibernate
		MAQ_NOM
		MAQ_SISOPE
		MAQ_ADRIP
		MAQ_ADRMAC
		MAQ_DESCRI
		MAQ_PARDHC
		MAQ_CORREU
		MAQ_OFIMAT
		MAQ_IDXAR: FK A XARXA (SC_XARXES) En teoría ya migrado
		MAQ_ALIAS

SC_ROLES
		ROL_ID: Autonumérico Hibernate
		ROL_NOM
		ROL_DESCRI
		ROL_IDAPL: FK a SC_APLICA
		ROL_DEFECT
		ROL_CONTRA
		ROL_IDDISPAT: NUEVO, DUDA ¿reemplaza a ROL_BD?
		ROL_DOMAPP
		ROL_TIPDOM
		ROL_BD: DUDA ¿copiamos ROL_BD? No se utiliza en Seycon 3.1
		
		DUDA: ¿Qué hacemos con la columna ROL_SUPER?, está siempre a N en seeduc

SC_ROLUSU
		RLU_ID: NUEVO Autonumérico Hibernate
		RLU_IDROL: FK a SC_ROLES
		RLU_IDUSU: FK a SC_USUARI
		RLU_ROLUSU_GRU: NUEVO
		RLU_ADMAPP: NUEVO
		RLU_VALDOM: NUEVO
		RLU_TIPDOM: NUEVO

SC_USUARI
		USU_ID: Autonumérico Hibernate
		USU_CODI
		USU_NOM
		USU_PRILLI
		USU_SEGLLI
		USU_NOMCUR
		USU_UNOFES
		USU_USUMOD
		USU_DATMOD
		USU_DATCRE
		USU_USUCRE
		USU_IDDCO: FK A SC_DOMCOR
		USU_IDGRU: FK A SC_GRUPS
		USU_IDMAQ: FK A SC_MAQUIN
		USU_IDMACO: FK A SC_MAQUIN 
		USU_IDMAPR: FK A SC_MAQUIN
		USU_ACTIU
		USU_ALCOAN
		USU_PEND
		USU_QUOTA
		USU_MULSES
		USU_COMENT
		USU_TIPUSU

SC_USUGRU
	UGR_IDGRU: FK A SC_GRUPS
	UGR_IDUSU: FK A SC_USUARI
	UGR_ID: NUEVO Autonumérico Hibernate

SC_USULCO 
	ULC_IDLCO: FK A SC_LLICOR 
	ULC_IDUSU: FK A SC_USUARI
	ULC_ID: NUEVO Autonumérico Hibernate

SC_XARXES
	Se supone que ya está migrado
		XAR_ID: Autonumérico Hibernate
		XAR_CODI
		XAR_ADRIP
		XAR_DESCRI
		XAR_MASIP
		XAR_NORM
		XAR_PARDHC




--- GENERAMOS UNA TABLA TEMPORAL PARA GUARDAR LOS IDS
		
CREATE TABLE SEYCON.TMP_SEEDUC
(
  IDNOU    NUMBER(10)                           NOT NULL,
  IDANTIC  NUMBER(10)                           NOT NULL,
  TAULA    VARCHAR2(40 CHAR)                    NOT NULL,
  NOU      VARCHAR2(1 CHAR)  DEFAULT 'S'
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
NOMONITORING;


ALTER TABLE SEYCON.TMP_SEEDUC ADD (
  CONSTRAINT TMP_SEEDUC_PK
 PRIMARY KEY
 (IDANTIC, TAULA));
		