// license-header java merge-point
//
// Attention: Generated code! Do not modify by hand!
// Generated by: SpringServiceLocator.vsl in andromda-spring-cartridge.
//
package es.caib.bpm.config;

import es.caib.seycon.ng.ServiceLocator;
import es.caib.seycon.ng.servei.SeyconServiceLocator;

/**
 * Locates and provides all available application services.
 */
public class BpmServiceLocator
{
    /**
     * Gets the shared instance of this Class
     *
     * @return the shared service locator instance.
     */
    public static final ServiceLocator instance()
    {
    	return SeyconServiceLocator.instance();
    }


}