package com.soffid.iam.doc.nas;

public class DocumentManagerErrorCodes {

	/** ERROR CODE PARA INDICAR QUE EL ROL NO EXISTE */
	public static int ROL_INEXISTENTE= 1000;
	/** ERROR CODE PARA INDICAR QUE EL METODO NO ESTA DISPONIBLE */
	public static int METODO_NO_DISPONIBLE= 1001;
	/** ERROR CODE PARA INDICAR QUE LA FIRMA NO ES VALIDA PARA EL DOCUMENTO */
	public static int ARCHIVO_FIRMA_INVALIDO= 1002;
	
	/** ERROR CODE PARA INDICAR QUE UNA EXCEPCION NO TIPIFICADA POR EL DOCUMENT MANAGER */
	public static int EXCEPCION_NO_TIPIFICADA= 9999;
}
