#!/bin/bash
cp -r /home/svives/git/console-2/selfservice/src/main/webapp/*     /opt/soffid/iam-console-2/work/soffid/iam-ear.ear/selfservice-2.0.0-SNAPSHOT/
cp -r /home/svives/git/console-2/selfservice/src/main/resources/*  /opt/soffid/iam-console-2/work/soffid/iam-ear.ear/selfservice-2.0.0-SNAPSHOT/WEB-INF/classes/

#rsync -vauz -e ssh /home/gbuades/soffid/console2/console/web/src/main/webapp/*		root@bubu.test.lab:/opt/soffid/iam-console/jboss/server/default/tmp/soffid/iam-ear.ear/iam-web-*.war
#rsync -vauz -e ssh /home/gbuades/soffid/console2/console/web/src/main/resources/*	root@bubu.test.lab:/opt/soffid/iam-console/jboss/server/default/tmp/soffid/iam-ear.ear/iam-web-*.war/WEB-INF/classes
