#!/bin/bash
cp -ru /home/gbuades/soffid/console/web/src/main/webapp/*    /home/gbuades/soffid/test/iam-console-3/work/soffid/iam-ear.ear/iam-web-*-SNAPSHOT/
cp -ru /home/gbuades/soffid/console/web/src/main/resources/* /home/gbuades/soffid/test/iam-console-3/work/soffid/iam-ear.ear/iam-web-*-SNAPSHOT/WEB-INF/classes/
#cp -ru /home/gbuades/soffid/console/web/target/classes/* /home/gbuades/soffid/test/iam-console-3/work/soffid/iam-ear.ear/iam-web-*-SNAPSHOT/WEB-INF/classes/
