#!/bin/bash
cp -r src/main/webapp/*    /home/gbuades/soffid-2.0/test/apache-tomee-plus-7.0.3/work/soffid/iam-ear.ear/iam-web-2.0.0-SNAPSHOT/
cp -r src/main/resources/* /home/gbuades/soffid-2.0/test/apache-tomee-plus-7.0.3/work/soffid/iam-ear.ear/iam-web-2.0.0-SNAPSHOT/WEB-INF/classes/
 
#rsync -vauz -e ssh /home/gbuades/soffid/console2/console/web/src/main/webapp/*		root@bubu.test.lab:/opt/soffid/iam-console/jboss/server/default/tmp/soffid/iam-ear.ear/iam-web-*.war
#rsync -vauz -e ssh /home/gbuades/soffid/console2/console/web/src/main/resources/*	root@bubu.test.lab:/opt/soffid/iam-console/jboss/server/default/tmp/soffid/iam-ear.ear/iam-web-*.war/WEB-INF/classes
